
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.43.0rc1'
version_full = '4868420e431184249a2db85a1ad88a60c88b7e51'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

