# Generated by Django 4.2.3 on 2023-07-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_notification', '0014_subscription_disable_automatic_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'default_permissions': ['add', 'change', 'delete', 'view', 'control'], 'ordering': ['pk']},
        ),
    ]
