"""creazione colonne per login history

Revision ID: 44fde88fa438
Revises: 6c9e84ab8280
Create Date: 2022-03-29 12:50:07.169962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fde88fa438'
down_revision = '6c9e84ab8280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppss_loginhistory', sa.Column('result', sa.Integer(), nullable=True))
    op.add_column('ppss_loginhistory', sa.Column('username', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ppss_loginhistory', 'username')
    op.drop_column('ppss_loginhistory', 'result')
    # ### end Alembic commands ###
