"""added email to user

Revision ID: 3f4032dd2d1b
Revises: 6190d529682d
Create Date: 2023-10-16 17:11:55.515679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4032dd2d1b'
down_revision = '6190d529682d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ppss_user', sa.Column('email', sa.Unicode(length=128), nullable=True))
    op.create_unique_constraint(op.f('uq_ppss_user_email'), 'ppss_user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ppss_user_email'), 'ppss_user', type_='unique')
    op.drop_column('ppss_user', 'email')
    # ### end Alembic commands ###
