# Generated by Django 4.2.11 on 2024-04-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bgtask", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundtask",
            name="namespace",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional namespace that can be used to avoid having to make names unique across an entire codebase, allowing them to be shorter and human readable",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="backgroundtask",
            name="name",
            field=models.CharField(
                help_text="Name (or type) of this task, is not unique per task instance but generally per task functionality",
                max_length=1000,
            ),
        ),
    ]
