from enum import Enum


class SenmlNames(Enum):
    ZUR_SENML_AS = "AS"
    ZUR_SENML_EBS = "EBS"
    ZUR_SENML_AMI = "AMI"
    ZUR_SENML_BRAKE = "brake"
    ZUR_SENML_BRAKE_FRONT = "brakeFront"
    ZUR_SENML_BRAKE_BACK = "brakeBack"
    ZUR_SENML_STEERING = "steering"
    ZUR_SENML_THROTTLE = "throttle"
    ZUR_SENML_THROTTLE_LEFT = "throttleLeft"
    ZUR_SENML_THROTTLE_RIGHT = "throttleRight"
    ZUR_SENML_STATUS = "status"
    ZUR_SENML_LAPS = "laps"
    ZUR_SENML_CONESACT = "conesAct"
    ZUR_SENML_CONESALL = "conesAll"
    ZUR_SENML_X = "x"
    ZUR_SENML_Y = "y"
    ZUR_SENML_Z = "z"
    ZUR_SENML_CONFIRMATION = "confirmation"
    ZUR_SENML_PING = "ping"
    ZUR_SENML_PEDAL = "pedal"
    ZUR_SENML_LVACCU = "LVAccu"
    ZUR_SENML_24V = "24V"
    ZUR_SENML_12V = "12V"
    ZUR_SENML_LVSHUTDOWN = "LVShutdown"
    ZUR_SENML_SENSOR = "sensor"
    ZUR_SENML_RESPONSE = "response"
    ZUR_SENML_REQUEST = "request"
    ZUR_SENML_CHARGE = "charge"
    ZUR_SENML_TEMP = "temp"
    ZUR_SENML_AIRPOS = "AIRPos"
    ZUR_SENML_AIRNEG = "AIRNeg"
    ZUR_SENML_PRERELAY = "preRelay"
    ZUR_SENML_MODESEL = "modeSel"
    ZUR_SENML_MODEACK = "modeACK"
    ZUR_SENML_RESET = "reset"

    ZUR_ECU_PEDAL_BASENAME = "ECU:pedal"
    ZUR_ECU_HVCB_BASENAME = "ECU/HVCB"
    ZUR_ECU_ACCU_BASENAME = "ECU:accu"
    ZUR_ECU_COCKPIT_BASENAME = "ECU:cockpit"
    ZUR_ECU_DV_BASENAME = "ECU:dv"
    ZUR_ECU_PING_BASENAME = "ECU:ping"
