from .main import number_plate_detection
from .main import genetic_algorithm
from .main import face_detection
from .main import three_cross_three_grid
from .main import three_cross_three_grid_rl
from .main import magic_square
from .main import genetic_algorithm_meghs
from .main import least_square_regression
from .main import k_means_clustering
from .main import k_means_ishan
from .main import binary_classification
from .main import least_square_regression_hithesh
from .main import import_statements