{# templates/config_swdomain.tpl #}

<?xml version="1.0" encoding="utf-8"?>
<?AutomationStudio FileVersion="4.9"?>
<!--autogenerated {{ timestamp }}-->
<Configuration>
  <Element ID="gSafeDomain" Type="sfdomain">
    <Group ID="DefaultSettings">
      <Property ID="SafeDomain" Value="1" />
      <Property ID="SafeLOGICName" Value="{{ sl8101_name }}" />
      <Property ID="SafeLOGICProductId" Value="X20cSL8101" />
      <Property ID="SafeLOGICModulePath" Value="IF3.ST32" />
      <Property ID="Password" Value="e10adc3949ba59abbe56e057f20f883e" />
      <Property ID="SafeProject" Value="safeZone" />
    </Group>
    <Group ID="DefaultFiles">
      <Property ID="TargetApplication" Value="safeZone.sfapp" />
    </Group>
  </Element>
</Configuration>
<!--end of autogenerated-->
