
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-13T09:53:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "812be8298b5ea324fcdfc9e71edae8dbe0aa8ae3",
 "version": "1.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
