import sys
import os

file_path = os.path.abspath(__file__)
end = file_path.index('mns') + 16
project_path = file_path[0:end]
sys.path.append(project_path)
import akshare as ak
from mns_common.db.MongodbUtil import MongodbUtil

mongodb_util = MongodbUtil('27017')


#
# {
#     "_id" : ObjectId("6644358f8eb1db9684c8b75d"),
#     "SECUCODE" : "600519.SH",
#     "SECURITY_CODE" : "600519",
#     "SECURITY_NAME_ABBR" : "贵州茅台",
#     "ORG_CODE" : "10002602",
#     "ORG_TYPE" : "通用",
#     "REPORT_DATE" : "2024-03-31 00:00:00",
#     "REPORT_TYPE" : "一季报",
#     "REPORT_DATE_NAME" : "2024一季报",
#     "SECURITY_TYPE_CODE" : "058001001",
#     "NOTICE_DATE" : "2024-04-27 00:00:00",
#     "UPDATE_DATE" : "2024-04-27 00:00:00",
#     "CURRENCY" : "CNY",
#     "ACCEPT_DEPOSIT_INTERBANK" : 8381544929.17,
#     "ACCOUNTS_PAYABLE" : 4022842219.54, 其中:应付账款
#     "ACCOUNTS_RECE" : 73124662.68, 应收账款
#     "ACCRUED_EXPENSE" : NaN,
#     "ADVANCE_RECEIVABLES" : NaN,
#     "AGENT_TRADE_SECURITY" : NaN,
#     "AGENT_UNDERWRITE_SECURITY" : NaN,
#     "AMORTIZE_COST_FINASSET" : NaN,
#     "AMORTIZE_COST_FINLIAB" : NaN,
#     "AMORTIZE_COST_NCFINASSET" : NaN,
#     "AMORTIZE_COST_NCFINLIAB" : NaN,
#     "APPOINT_FVTPL_FINASSET" : NaN,
#     "APPOINT_FVTPL_FINLIAB" : NaN,
#     "ASSET_BALANCE" : 0.0,
#     "ASSET_OTHER" : NaN,
#     "ASSIGN_CASH_DIVIDEND" : NaN,
#     "AVAILABLE_SALE_FINASSET" : NaN,
#     "BOND_PAYABLE" : NaN,
#     "BORROW_FUND" : NaN,
#     "BUY_RESALE_FINASSET" : 7111997692.87, 买入返售金融资产
#     "CAPITAL_RESERVE" : 1374964415.72, 资本公积
#     "CIP" : 2813289076.98, 在建工程
#     "CONSUMPTIVE_BIOLOGICAL_ASSET" : NaN,
#     "CONTRACT_ASSET" : NaN,
#     "CONTRACT_LIAB" : 9523298229.75, 合同负债
#     "CONVERT_DIFF" : NaN,
#     "CREDITOR_INVEST" : 5335437085.68, 债权投资
#     "CURRENT_ASSET_BALANCE" : 0.0,
#     "CURRENT_ASSET_OTHER" : NaN,
#     "CURRENT_LIAB_BALANCE" : 0.0,
#     "CURRENT_LIAB_OTHER" : NaN,
#     "DEFER_INCOME" : NaN,
#     "DEFER_INCOME_1YEAR" : NaN,
#     "DEFER_TAX_ASSET" : 4477172963.01, 递延所得税资产
#     "DEFER_TAX_LIAB" : 80835441.75, 递延所得税负债
#     "DERIVE_FINASSET" : NaN,
#     "DERIVE_FINLIAB" : NaN,
#     "DEVELOP_EXPENSE" : 222425799.33, 开发支出
#     "DIV_HOLDSALE_ASSET" : NaN,
#     "DIV_HOLDSALE_LIAB" : NaN,
#     "DIVIDEND_PAYABLE" : NaN,
#     "DIVIDEND_RECE" : NaN,
#     "EQUITY_BALANCE" : 0.0,
#     "EQUITY_OTHER" : NaN,
#     "EXPORT_REFUND_RECE" : NaN,
#     "FEE_COMMISSION_PAYABLE" : NaN,
#     "FIN_FUND" : NaN,
#     "FINANCE_RECE" : NaN,
#     "FIXED_ASSET" : 19541551054.14, 固定资产
#     "FIXED_ASSET_DISPOSAL" : NaN,
#     "FVTOCI_FINASSET" : NaN,
#     "FVTOCI_NCFINASSET" : NaN,
#     "FVTPL_FINASSET" : NaN,
#     "FVTPL_FINLIAB" : NaN,
#     "GENERAL_RISK_RESERVE" : 1061529724.0, 一般风险准备
#     "GOODWILL" : NaN,
#     "HOLD_MATURITY_INVEST" : NaN,
#     "HOLDSALE_ASSET" : NaN,
#     "HOLDSALE_LIAB" : NaN,
#     "INSURANCE_CONTRACT_RESERVE" : NaN,
#     "INTANGIBLE_ASSET" : 8517877019.46, 无形资产
#     "INTEREST_PAYABLE" : NaN,
#     "INTEREST_RECE" : NaN,
#     "INTERNAL_PAYABLE" : NaN,
#     "INTERNAL_RECE" : NaN,
#     "INVENTORY" : 46852227606.93, 存货
#     "INVEST_REALESTATE" : 3959373.06, 投资性房地产
#     "LEASE_LIAB" : 280265260.71, 租赁负债
#     "LEND_FUND" : 105060937860.99,  拆出资金
#     "LIAB_BALANCE" : 0.0,
#     "LIAB_EQUITY_BALANCE" : NaN,
#     "LIAB_EQUITY_OTHER" : NaN,
#     "LIAB_OTHER" : NaN,
#     "LOAN_ADVANCE" : 2603796544.91, 发放贷款及垫款
#     "LOAN_PBC" : NaN,
#     "LONG_EQUITY_INVEST" : NaN,
#     "LONG_LOAN" : NaN,
#     "LONG_PAYABLE" : NaN,
#     "LONG_PREPAID_EXPENSE" : 157773820.24, 长期待摊费用
#     "LONG_RECE" : NaN,
#     "LONG_STAFFSALARY_PAYABLE" : NaN,
#     "MINORITY_EQUITY" : 8804982639.98, 少数股东权益
#     "MONETARYFUNDS" : 74197126391.43,   货币资金
#     "NONCURRENT_ASSET_1YEAR" : NaN,
#     "NONCURRENT_ASSET_BALANCE" : 0.0,
#     "NONCURRENT_ASSET_OTHER" : NaN,
#     "NONCURRENT_LIAB_1YEAR" : 56128002.7, 一年内到期的非流动负债
#     "NONCURRENT_LIAB_BALANCE" : 0.0,
#     "NONCURRENT_LIAB_OTHER" : NaN,
#     "NOTE_ACCOUNTS_PAYABLE" : 4022842219.54,  应付票据及应付账款
#     "NOTE_ACCOUNTS_RECE" : 213804940.68,应收票据及应收账款 总
#     "NOTE_PAYABLE" : NaN,
#     "NOTE_RECE" : 140680278.0, 应收票据
#     "OIL_GAS_ASSET" : NaN,
#     "OTHER_COMPRE_INCOME" : -8109798.54, 其他综合收益
#     "OTHER_CREDITOR_INVEST" : NaN,
#     "OTHER_CURRENT_ASSET" : 61062481.87, 其他流动资产
#     "OTHER_CURRENT_LIAB" : 1145591991.93, 其他流动负债
#     "OTHER_EQUITY_INVEST" : NaN,
#     "OTHER_EQUITY_OTHER" : NaN,
#     "OTHER_EQUITY_TOOL" : NaN,
#     "OTHER_NONCURRENT_ASSET" : 154011277.63, 其他非流动资产
#     "OTHER_NONCURRENT_FINASSET" : 4004528610.65, 其他非流动金融资产
#     "OTHER_NONCURRENT_LIAB" : NaN,
#     "OTHER_PAYABLE" : NaN,
#     "OTHER_RECE" : NaN,
#     "PARENT_EQUITY_BALANCE" : 0.0,
#     "PARENT_EQUITY_OTHER" : NaN,
#     "PERPETUAL_BOND" : NaN,
#     "PERPETUAL_BOND_PAYBALE" : NaN,
#     "PREDICT_CURRENT_LIAB" : NaN,
#     "PREDICT_LIAB" : NaN,
#     "PREFERRED_SHARES" : NaN,
#     "PREFERRED_SHARES_PAYBALE" : NaN,
#     "PREMIUM_RECE" : NaN,
#     "PREPAYMENT" : 41204652.37, 预付款项
#     "PRODUCTIVE_BIOLOGY_ASSET" : NaN,
#     "PROJECT_MATERIAL" : NaN,
#     "RC_RESERVE_RECE" : NaN,
#     "REINSURE_PAYABLE" : NaN,
#     "REINSURE_RECE" : NaN,
#     "SELL_REPO_FINASSET" : NaN,
#     "SETTLE_EXCESS_RESERVE" : NaN,
#     "SHARE_CAPITAL" : 1256197800.0, 实收资本（或股本）
#     "SHORT_BOND_PAYABLE" : NaN,
#     "SHORT_FIN_PAYABLE" : NaN,
#     "SHORT_LOAN" : NaN,
#     "SPECIAL_PAYABLE" : NaN,
#     "SPECIAL_RESERVE" : NaN,
#     "STAFF_SALARY_PAYABLE" : 764260631.72, 应付职工薪酬
#     "SUBSIDY_RECE" : NaN,
#     "SURPLUS_RESERVE" : 38998763095.13, 盈余公积
#     "TAX_PAYABLE" : 7015986396.93, 应交税费
#     "TOTAL_ASSETS" : 285524543268.38, 资产总计
#     "TOTAL_CURRENT_ASSETS" : 237376996384.72,  流动资产合计
#     "TOTAL_CURRENT_LIAB" : 36626674015.39, 流动负债合计
#     "TOTAL_EQUITY" : 248536768550.53, 股东权益合计
#     "TOTAL_LIAB_EQUITY" : 285524543268.38, 负债和股东权益总计
#     "TOTAL_LIABILITIES" : 36987774717.85, 负债合计
#     "TOTAL_NONCURRENT_ASSETS" : 48147546883.66, 非流动资产合计
#     "TOTAL_NONCURRENT_LIAB" : 361100702.46, 非流动负债合计
#     "TOTAL_OTHER_PAYABLE" : 5717021613.65, 其他应付款合计
#     "TOTAL_OTHER_RECE" : 26297328.18, 其他应收款合计
#     "TOTAL_PARENT_EQUITY" : 239731785910.55, 归属于母公司股东权益总计
#     "TRADE_FINASSET" : NaN,
#     "TRADE_FINASSET_NOTFVTPL" : 3812337429.4, 交易性金融资产
#     "TRADE_FINLIAB" : NaN,
#     "TRADE_FINLIAB_NOTFVTPL" : NaN,
#     "TREASURY_SHARES" : NaN,
#     "UNASSIGN_RPOFIT" : 197048440674.24, 未分配利润
#     "UNCONFIRM_INVEST_LOSS" : NaN,
#     "USERIGHT_ASSET" : 315724258.57, 使用权资产
#     "ACCEPT_DEPOSIT_INTERBANK_YOY" : 6.5949245759,
#     "ACCOUNTS_PAYABLE_YOY" : 52.3685299106,
#     "ACCOUNTS_RECE_YOY" : 25.1911350968,
#     "ACCRUED_EXPENSE_YOY" : NaN,
#     "ADVANCE_RECEIVABLES_YOY" : NaN,
#     "AGENT_TRADE_SECURITY_YOY" : NaN,
#     "AGENT_UNDERWRITE_SECURITY_YOY" : NaN,
#     "AMORTIZE_COST_FINASSET_YOY" : NaN,
#     "AMORTIZE_COST_FINLIAB_YOY" : NaN,
#     "AMORTIZE_COST_NCFINASSET_YOY" : NaN,
#     "AMORTIZE_COST_NCFINLIAB_YOY" : NaN,
#     "APPOINT_FVTPL_FINASSET_YOY" : NaN,
#     "APPOINT_FVTPL_FINLIAB_YOY" : NaN,
#     "ASSET_BALANCE_YOY" : NaN,
#     "ASSET_OTHER_YOY" : NaN,
#     "ASSIGN_CASH_DIVIDEND_YOY" : NaN,
#     "AVAILABLE_SALE_FINASSET_YOY" : NaN,
#     "BOND_PAYABLE_YOY" : NaN,
#     "BORROW_FUND_YOY" : NaN,
#     "BUY_RESALE_FINASSET_YOY" : NaN,
#     "CAPITAL_RESERVE_YOY" : 0.0,
#     "CIP_YOY" : 16.3686330752,
#     "CONSUMPTIVE_BIOLOGICAL_ASSET_YOY" : NaN,
#     "CONTRACT_ASSET_YOY" : NaN,
#     "CONTRACT_LIAB_YOY" : 14.3255118595,
#     "CONVERT_DIFF_YOY" : NaN,
#     "CREDITOR_INVEST_YOY" : 285.3261659949,
#     "CURRENT_ASSET_BALANCE_YOY" : NaN,
#     "CURRENT_ASSET_OTHER_YOY" : NaN,
#     "CURRENT_LIAB_BALANCE_YOY" : NaN,
#     "CURRENT_LIAB_OTHER_YOY" : NaN,
#     "DEFER_INCOME_1YEAR_YOY" : NaN,
#     "DEFER_INCOME_YOY" : NaN,
#     "DEFER_TAX_ASSET_YOY" : 28.901621248,
#     "DEFER_TAX_LIAB_YOY" : -50.2942934041,
#     "DERIVE_FINASSET_YOY" : NaN,
#     "DERIVE_FINLIAB_YOY" : NaN,
#     "DEVELOP_EXPENSE_YOY" : 2.5846179105,
#     "DIV_HOLDSALE_ASSET_YOY" : NaN,
#     "DIV_HOLDSALE_LIAB_YOY" : NaN,
#     "DIVIDEND_PAYABLE_YOY" : NaN,
#     "DIVIDEND_RECE_YOY" : NaN,
#     "EQUITY_BALANCE_YOY" : NaN,
#     "EQUITY_OTHER_YOY" : NaN,
#     "EXPORT_REFUND_RECE_YOY" : NaN,
#     "FEE_COMMISSION_PAYABLE_YOY" : NaN,
#     "FIN_FUND_YOY" : NaN,
#     "FINANCE_RECE_YOY" : NaN,
#     "FIXED_ASSET_DISPOSAL_YOY" : NaN,
#     "FIXED_ASSET_YOY" : 0.2675488842,
#     "FVTOCI_FINASSET_YOY" : NaN,
#     "FVTOCI_NCFINASSET_YOY" : NaN,
#     "FVTPL_FINASSET_YOY" : NaN,
#     "FVTPL_FINLIAB_YOY" : NaN,
#     "GENERAL_RISK_RESERVE_YOY" : 0.0,
#     "GOODWILL_YOY" : NaN,
#     "HOLD_MATURITY_INVEST_YOY" : NaN,
#     "HOLDSALE_ASSET_YOY" : NaN,
#     "HOLDSALE_LIAB_YOY" : NaN,
#     "INSURANCE_CONTRACT_RESERVE_YOY" : NaN,
#     "INTANGIBLE_ASSET_YOY" : 1.0527955969,
#     "INTEREST_PAYABLE_YOY" : NaN,
#     "INTEREST_RECE_YOY" : NaN,
#     "INTERNAL_PAYABLE_YOY" : NaN,
#     "INTERNAL_RECE_YOY" : NaN,
#     "INVENTORY_YOY" : 16.9761008245,
#     "INVEST_REALESTATE_YOY" : -13.4284669865,
#     "LEASE_LIAB_YOY" : -16.5811741118,
#     "LEND_FUND_YOY" : -0.3509101173,
#     "LIAB_BALANCE_YOY" : NaN,
#     "LIAB_EQUITY_BALANCE_YOY" : NaN,
#     "LIAB_EQUITY_OTHER_YOY" : NaN,
#     "LIAB_OTHER_YOY" : NaN,
#     "LOAN_ADVANCE_YOY" : -38.6288828825,
#     "LOAN_PBC_YOY" : NaN,
#     "LONG_EQUITY_INVEST_YOY" : NaN,
#     "LONG_LOAN_YOY" : NaN,
#     "LONG_PAYABLE_YOY" : NaN,
#     "LONG_PREPAID_EXPENSE_YOY" : 8.0142948307,
#     "LONG_RECE_YOY" : NaN,
#     "LONG_STAFFSALARY_PAYABLE_YOY" : NaN,
#     "MINORITY_EQUITY_YOY" : 7.5367435942,
#     "MONETARYFUNDS_YOY" : 2.4104551404,
#     "NONCURRENT_ASSET_1YEAR_YOY" : NaN,
#     "NONCURRENT_ASSET_BALANCE_YOY" : NaN,
#     "NONCURRENT_ASSET_OTHER_YOY" : NaN,
#     "NONCURRENT_LIAB_1YEAR_YOY" : -37.7830800373,
#     "NONCURRENT_LIAB_BALANCE_YOY" : NaN,
#     "NONCURRENT_LIAB_OTHER_YOY" : NaN,
#     "NOTE_ACCOUNTS_PAYABLE_YOY" : 52.3685299106,
#     "NOTE_ACCOUNTS_RECE_YOY" : 266.0390657824,
#     "NOTE_PAYABLE_YOY" : NaN,
#     "NOTE_RECE_YOY" : NaN,
#     "OIL_GAS_ASSET_YOY" : NaN,
#     "OTHER_COMPRE_INCOME_YOY" : 18.9797836371,
#     "OTHER_CREDITOR_INVEST_YOY" : NaN,
#     "OTHER_CURRENT_ASSET_YOY" : -23.5699370064,
#     "OTHER_CURRENT_LIAB_YOY" : 16.8415197677,
#     "OTHER_EQUITY_INVEST_YOY" : NaN,
#     "OTHER_EQUITY_OTHER_YOY" : NaN,
#     "OTHER_EQUITY_TOOL_YOY" : NaN,
#     "OTHER_NONCURRENT_ASSET_YOY" : NaN,
#     "OTHER_NONCURRENT_FINASSET_YOY" : NaN,
#     "OTHER_NONCURRENT_LIAB_YOY" : NaN,
#     "OTHER_PAYABLE_YOY" : NaN,
#     "OTHER_RECE_YOY" : NaN,
#     "PARENT_EQUITY_BALANCE_YOY" : NaN,
#     "PARENT_EQUITY_OTHER_YOY" : NaN,
#     "PERPETUAL_BOND_PAYBALE_YOY" : NaN,
#     "PERPETUAL_BOND_YOY" : NaN,
#     "PREDICT_CURRENT_LIAB_YOY" : NaN,
#     "PREDICT_LIAB_YOY" : NaN,
#     "PREFERRED_SHARES_PAYBALE_YOY" : NaN,
#     "PREFERRED_SHARES_YOY" : NaN,
#     "PREMIUM_RECE_YOY" : NaN,
#     "PREPAYMENT_YOY" : -56.3999888135,
#     "PRODUCTIVE_BIOLOGY_ASSET_YOY" : NaN,
#     "PROJECT_MATERIAL_YOY" : NaN,
#     "RC_RESERVE_RECE_YOY" : NaN,
#     "REINSURE_PAYABLE_YOY" : NaN,
#     "REINSURE_RECE_YOY" : NaN,
#     "SELL_REPO_FINASSET_YOY" : NaN,
#     "SETTLE_EXCESS_RESERVE_YOY" : NaN,
#     "SHARE_CAPITAL_YOY" : 0.0,
#     "SHORT_BOND_PAYABLE_YOY" : NaN,
#     "SHORT_FIN_PAYABLE_YOY" : NaN,
#     "SHORT_LOAN_YOY" : NaN,
#     "SPECIAL_PAYABLE_YOY" : NaN,
#     "SPECIAL_RESERVE_YOY" : NaN,
#     "STAFF_SALARY_PAYABLE_YOY" : 71.7783411719,
#     "SUBSIDY_RECE_YOY" : NaN,
#     "SURPLUS_RESERVE_YOY" : 19.9219406872,
#     "TAX_PAYABLE_YOY" : 2.2341617814,
#     "TOTAL_ASSETS_YOY" : 10.501055862,
#     "TOTAL_CURRENT_ASSETS_YOY" : 8.7885311339,
#     "TOTAL_CURRENT_LIAB_YOY" : 16.5392858116,
#     "TOTAL_EQUITY_YOY" : 9.7469071685,
#     "TOTAL_LIAB_EQUITY_YOY" : 10.501055862,
#     "TOTAL_LIABILITIES_YOY" : 15.8503242759,
#     "TOTAL_NONCURRENT_ASSETS_YOY" : 19.7986394071,
#     "TOTAL_NONCURRENT_LIAB_YOY" : -27.5773258656,
#     "TOTAL_OTHER_PAYABLE_YOY" : 35.5651942454,
#     "TOTAL_OTHER_RECE_YOY" : -20.5943342049,
#     "TOTAL_PARENT_EQUITY_YOY" : 9.8298140667,
#     "TRADE_FINASSET_NOTFVTPL_YOY" : NaN,
#     "TRADE_FINASSET_YOY" : NaN,
#     "TRADE_FINLIAB_NOTFVTPL_YOY" : NaN,
#     "TRADE_FINLIAB_YOY" : NaN,
#     "TREASURY_SHARES_YOY" : NaN,
#     "UNASSIGN_RPOFIT_YOY" : 8.225033105,
#     "UNCONFIRM_INVEST_LOSS_YOY" : NaN,
#     "USERIGHT_ASSET_YOY" : -18.2349946142,
#     "OPINION_TYPE" : null, 审计意见(境内)
#     "OSOPINION_TYPE" : NaN,
#     "LISTING_STATE" : "0"
# }

# 资产负债表
# https://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/Index?type=web&code=sh600519#zcfzb-0
def get_em_debt_api(symbol):
    stock_balance_sheet_by_report_em_df = ak.stock_balance_sheet_by_report_em(symbol)
    stock_balance_sheet_by_report_em_df = stock_balance_sheet_by_report_em_df[[
        'SECUCODE',
        'SECURITY_CODE',
        'SECURITY_NAME_ABBR',
        'ORG_CODE',
        'ORG_TYPE',
        'REPORT_DATE',
        'REPORT_TYPE',
        'REPORT_DATE_NAME',
        'SECURITY_TYPE_CODE',
        'NOTICE_DATE',
        'UPDATE_DATE',
        'CURRENCY',
        'ACCOUNTS_PAYABLE',
        'ACCOUNTS_RECE',
        'BUY_RESALE_FINASSET',
        'CAPITAL_RESERVE',
        'CIP',
        'CONTRACT_LIAB',
        'CREDITOR_INVEST',
        'DEFER_TAX_ASSET',
        'DEFER_TAX_LIAB',
        'DEVELOP_EXPENSE',
        'FIXED_ASSET',
        'GENERAL_RISK_RESERVE',
        'INTANGIBLE_ASSET',
        'INVENTORY',
        'INVEST_REALESTATE',
        'LEASE_LIAB',
        'LEND_FUND',
        'LOAN_ADVANCE',
        'LONG_PREPAID_EXPENSE',
        'MINORITY_EQUITY',
        'MONETARYFUNDS',
        'NONCURRENT_LIAB_1YEAR',
        'NOTE_ACCOUNTS_PAYABLE',
        'NOTE_ACCOUNTS_RECE',
        'NOTE_RECE',
        'OTHER_COMPRE_INCOME',
        'OTHER_CURRENT_ASSET',
        'OTHER_CURRENT_LIAB',
        'OTHER_NONCURRENT_ASSET',
        'OTHER_NONCURRENT_FINASSET',
        'PREPAYMENT',
        'SHARE_CAPITAL',
        'STAFF_SALARY_PAYABLE',
        'SURPLUS_RESERVE',
        'TAX_PAYABLE',
        'TOTAL_ASSETS',
        'TOTAL_CURRENT_ASSETS',
        'TOTAL_CURRENT_LIAB',
        'TOTAL_EQUITY',
        'TOTAL_LIAB_EQUITY',
        'TOTAL_LIABILITIES',
        'TOTAL_NONCURRENT_ASSETS',
        'TOTAL_NONCURRENT_LIAB',
        'TOTAL_OTHER_PAYABLE',
        'TOTAL_OTHER_RECE',
        'TOTAL_PARENT_EQUITY',
        'TRADE_FINASSET_NOTFVTPL',
        'UNASSIGN_RPOFIT',
        'USERIGHT_ASSET',
        'OPINION_TYPE'
    ]]
    print(stock_balance_sheet_by_report_em_df)
    mongodb_util.insert_mongo(stock_balance_sheet_by_report_em_df, 'stock_balance_sheet_by_report_em_df')


# 利润表
#  "_id" : ObjectId("6644085f608b7737dee21a3a"),
#     "SECUCODE" : "600519.SH",
#     "SECURITY_CODE" : "600519",
#     "SECURITY_NAME_ABBR" : "贵州茅台",
#     "ORG_CODE" : "10002602",
#     "ORG_TYPE" : "通用",
#     "REPORT_DATE" : "2023-12-31 00:00:00",
#     "REPORT_TYPE" : "年报",
#     "REPORT_DATE_NAME" : "2023年报",
#     "SECURITY_TYPE_CODE" : "058001001",
#     "NOTICE_DATE" : "2024-04-03 00:00:00",
#     "UPDATE_DATE" : "2024-04-03 00:00:00",
#     "CURRENCY" : "CNY",
#     "TOTAL_OPERATE_INCOME" : 150560330316.45,  营业总收入
#     "TOTAL_OPERATE_INCOME_YOY" : 18.0365792459, 总运营收入修正
#     "OPERATE_INCOME" : 147693604994.14,  营业收入
#     "OPERATE_INCOME_YOY" : 19.0119185529, 营业收入修正
#     "INTEREST_INCOME" : 2866725322.31, 利息收入
#     "INTEREST_INCOME_YOY" : 利息收入修正
#     "EARNED_PREMIUM" : NaN,
#     "EARNED_PREMIUM_YOY" : NaN,
#     "FEE_COMMISSION_INCOME" : NaN,
#     "FEE_COMMISSION_INCOME_YOY" : NaN,
#     "OTHER_BUSINESS_INCOME" : NaN,
#     "OTHER_BUSINESS_INCOME_YOY" : NaN,
#     "TOI_OTHER" : NaN,
#     "TOI_OTHER_YOY" : NaN,
#     "TOTAL_OPERATE_COST" : 46960889468.54, 营业总成本
#     "TOTAL_OPERATE_COST_YOY" : 18.1456266222,
#     "OPERATE_COST" : 11867273851.78, 营业成本
#     "OPERATE_COST_YOY" : 17.5737925437,
#     "INTEREST_EXPENSE" : 113500129.93, 利息支出
#     "INTEREST_EXPENSE_YOY" : 7.4972611642,
#     "FEE_COMMISSION_EXPENSE" : 68578.57,  手续费及佣金支出
#     "FEE_COMMISSION_EXPENSE_YOY" : -52.0903684752,
#     "RESEARCH_EXPENSE" : 157371873.01, 研发费用
#     "RESEARCH_EXPENSE_YOY" : 16.4116440028,
#     "SURRENDER_VALUE" : NaN,
#     "SURRENDER_VALUE_YOY" : NaN,
#     "NET_COMPENSATE_EXPENSE" : NaN,
#     "NET_COMPENSATE_EXPENSE_YOY" : NaN,
#     "NET_CONTRACT_RESERVE" : NaN,
#     "NET_CONTRACT_RESERVE_YOY" : NaN,
#     "POLICY_BONUS_EXPENSE" : NaN,
#     "POLICY_BONUS_EXPENSE_YOY" : NaN,
#     "REINSURE_EXPENSE" : NaN,
#     "REINSURE_EXPENSE_YOY" : NaN,
#     "OTHER_BUSINESS_COST" : NaN,
#     "OTHER_BUSINESS_COST_YOY" : NaN,
#     "OPERATE_TAX_ADD" : 22234175898.6, 税金及附加
#     "OPERATE_TAX_ADD_YOY" : 20.2119055043,
#     "SALE_EXPENSE" : 4648613585.82, 销售费用
#     "SALE_EXPENSE_YOY" : 40.9642928475,
#     "MANAGE_EXPENSE" : 9729389252.31, 管理费用
#     "MANAGE_EXPENSE_YOY" : 7.9580889133,
#     "ME_RESEARCH_EXPENSE" : NaN,
#     "ME_RESEARCH_EXPENSE_YOY" : NaN,
#     "FINANCE_EXPENSE" : -1789503701.48, 财务费用
#     "FINANCE_EXPENSE_YOY" : -28.5742355094,
#     "FE_INTEREST_EXPENSE" : 12624628.35, 利息费用
#     "FE_INTEREST_EXPENSE_YOY" : 5.0021902771,
#     "FE_INTEREST_INCOME" : 1942301920.98, 利息收入
#     "FE_INTEREST_INCOME_YOY" : 31.6437955552,
#     "ASSET_IMPAIRMENT_LOSS" : NaN,
#     "ASSET_IMPAIRMENT_LOSS_YOY" : NaN,
#     "CREDIT_IMPAIRMENT_LOSS" : NaN,
#     "CREDIT_IMPAIRMENT_LOSS_YOY" : NaN,
#     "TOC_OTHER" : NaN,
#     "TOC_OTHER_YOY" : NaN,
#     "FAIRVALUE_CHANGE_INCOME" : 3151962.5, :公允价值变动收益
#     "FAIRVALUE_CHANGE_INCOME_YOY" : NaN,
#     "INVEST_INCOME" : 34025967.82, 投资收益
#     "INVEST_INCOME_YOY" : -46.7011782268,
#     "INVEST_JOINT_INCOME" : NaN,
#     "INVEST_JOINT_INCOME_YOY" : NaN,
#     "NET_EXPOSURE_INCOME" : NaN,
#     "NET_EXPOSURE_INCOME_YOY" : NaN,
#     "EXCHANGE_INCOME" : NaN,
#     "EXCHANGE_INCOME_YOY" : NaN,
#     "ASSET_DISPOSAL_INCOME" : -479736.97, 资产处置收益
#     "ASSET_DISPOSAL_INCOME_YOY" : -324.9796785895,
#     "ASSET_IMPAIRMENT_INCOME" : NaN,
#     "ASSET_IMPAIRMENT_INCOME_YOY" : NaN,
#     "CREDIT_IMPAIRMENT_INCOME" : 37871293.26, 信用减值损失(新)
#     "CREDIT_IMPAIRMENT_INCOME_YOY" : 357.8638477375,
#     "OTHER_INCOME" : 34644873.86, 其他收益
#     "OTHER_INCOME_YOY" : 41.3767542405,
#     "OPERATE_PROFIT_OTHER" : NaN,
#     "OPERATE_PROFIT_OTHER_YOY" : NaN,
#     "OPERATE_PROFIT_BALANCE" : 0.0,
#     "OPERATE_PROFIT_BALANCE_YOY" : NaN,
#     "OPERATE_PROFIT" : 103708655208.38, 营业利润
#     "OPERATE_PROFIT_YOY" : 18.0123117479,
#     "NONBUSINESS_INCOME" : 86779655.95, 加:营业外收入
#     "NONBUSINESS_INCOME_YOY" : 22.4796849672,
#     "NONCURRENT_DISPOSAL_INCOME" : NaN,
#     "NONCURRENT_DISPOSAL_INCOME_YOY" : NaN,
#     "NONBUSINESS_EXPENSE" : 132881174.52, 减:营业外支出
#     "NONBUSINESS_EXPENSE_YOY" : -46.6092621953,
#     "NONCURRENT_DISPOSAL_LOSS" : NaN,
#     "NONCURRENT_DISPOSAL_LOSS_YOY" : NaN,
#     "EFFECT_TP_OTHER" : NaN,
#     "EFFECT_TP_OTHER_YOY" : NaN,
#     "TOTAL_PROFIT_BALANCE" : 0.0,
#     "TOTAL_PROFIT_BALANCE_YOY" : NaN,
#     "TOTAL_PROFIT" : 103662553689.81, 利润总额
#     "TOTAL_PROFIT_YOY" : 18.1993076599,
#     "INCOME_TAX" : 26141077412.01, 减:所得税
#     "INCOME_TAX_YOY" : 17.0909328034,
#     "EFFECT_NETPROFIT_OTHER" : NaN,
#     "EFFECT_NETPROFIT_OTHER_YOY" : NaN,
#     "EFFECT_NETPROFIT_BALANCE" : NaN,
#     "EFFECT_NETPROFIT_BALANCE_YOY" : NaN,
#     "UNCONFIRM_INVEST_LOSS" : NaN,
#     "UNCONFIRM_INVEST_LOSS_YOY" : NaN,
#     "NETPROFIT" : 77521476277.8, 净利润
#     "NETPROFIT_YOY" : 18.5778097415,
#     "PRECOMBINE_PROFIT" : NaN,
#     "PRECOMBINE_PROFIT_YOY" : NaN,
#     "CONTINUED_NETPROFIT" : 77521476277.8, 持续经营净利润
#     "CONTINUED_NETPROFIT_YOY" : 18.5778097415,
#     "DISCONTINUED_NETPROFIT" : NaN,
#     "DISCONTINUED_NETPROFIT_YOY" : NaN,
#     "PARENT_NETPROFIT" : 74734071550.75, 归属于母公司股东的净利润
#     "PARENT_NETPROFIT_YOY" : 19.1598992892,
#     "MINORITY_INTEREST" : 2787404727.05,  少数股东损益
#     "MINORITY_INTEREST_YOY" : 4.8459336455,
#     "DEDUCT_PARENT_NETPROFIT" : 74752564425.52, 扣除非经常性损益后的净利润
#     "DEDUCT_PARENT_NETPROFIT_YOY" : 19.0462109566,
#     "NETPROFIT_OTHER" : NaN,
#     "NETPROFIT_OTHER_YOY" : NaN,
#     "NETPROFIT_BALANCE" : NaN,
#     "NETPROFIT_BALANCE_YOY" : NaN,
#     "BASIC_EPS" : 59.49,  基本每股收益
#     "BASIC_EPS_YOY" : 19.1468055277,
#     "DILUTED_EPS" : 59.49,  稀释每股收益
#     "DILUTED_EPS_YOY" : 19.1468055277,
#     "OTHER_COMPRE_INCOME" : 4715179.82, 其他综合收益
#     "OTHER_COMPRE_INCOME_YOY" : 110.40766101,
#     "PARENT_OCI" : 4715179.82, 归属于母公司股东的其他综合收益
#     "PARENT_OCI_YOY" : 110.40766101,
#     "MINORITY_OCI" : NaN,
#     "MINORITY_OCI_YOY" : NaN,
#     "PARENT_OCI_OTHER" : NaN,
#     "PARENT_OCI_OTHER_YOY" : NaN,
#     "PARENT_OCI_BALANCE" : NaN,
#     "PARENT_OCI_BALANCE_YOY" : NaN,
#     "UNABLE_OCI" : NaN,
#     "UNABLE_OCI_YOY" : NaN,
#     "CREDITRISK_FAIRVALUE_CHANGE" : NaN,
#     "CREDITRISK_FAIRVALUE_CHANGE_YOY" : NaN,
#     "OTHERRIGHT_FAIRVALUE_CHANGE" : NaN,
#     "OTHERRIGHT_FAIRVALUE_CHANGE_YOY" : NaN,
#     "SETUP_PROFIT_CHANGE" : NaN,
#     "SETUP_PROFIT_CHANGE_YOY" : NaN,
#     "RIGHTLAW_UNABLE_OCI" : NaN,
#     "RIGHTLAW_UNABLE_OCI_YOY" : NaN,
#     "UNABLE_OCI_OTHER" : NaN,
#     "UNABLE_OCI_OTHER_YOY" : NaN,
#     "UNABLE_OCI_BALANCE" : NaN,
#     "UNABLE_OCI_BALANCE_YOY" : NaN,
#     "ABLE_OCI" : 4715179.82,
#     "ABLE_OCI_YOY" : 110.40766101,
#     "RIGHTLAW_ABLE_OCI" : NaN,
#     "RIGHTLAW_ABLE_OCI_YOY" : NaN,
#     "AFA_FAIRVALUE_CHANGE" : NaN,
#     "AFA_FAIRVALUE_CHANGE_YOY" : NaN,
#     "HMI_AFA" : NaN,
#     "HMI_AFA_YOY" : NaN,
#     "CASHFLOW_HEDGE_VALID" : NaN,
#     "CASHFLOW_HEDGE_VALID_YOY" : NaN,
#     "CREDITOR_FAIRVALUE_CHANGE" : NaN,
#     "CREDITOR_FAIRVALUE_CHANGE_YOY" : NaN,
#     "CREDITOR_IMPAIRMENT_RESERVE" : NaN,
#     "CREDITOR_IMPAIRMENT_RESERVE_YOY" : NaN,
#     "FINANCE_OCI_AMT" : NaN,
#     "FINANCE_OCI_AMT_YOY" : NaN,
#     "CONVERT_DIFF" : 4715179.82,
#     "CONVERT_DIFF_YOY" : 110.40766101,
#     "ABLE_OCI_OTHER" : NaN,
#     "ABLE_OCI_OTHER_YOY" : NaN,
#     "ABLE_OCI_BALANCE" : NaN,
#     "ABLE_OCI_BALANCE_YOY" : NaN,
#     "OCI_OTHER" : NaN,
#     "OCI_OTHER_YOY" : NaN,
#     "OCI_BALANCE" : NaN,
#     "OCI_BALANCE_YOY" : NaN,
#     "TOTAL_COMPRE_INCOME" : 77526191457.62, 综合收益总额
#     "TOTAL_COMPRE_INCOME_YOY" : 18.5809573963,
#     "PARENT_TCI" : 74738786730.57, 归属于母公司股东的综合收益总额
#     "PARENT_TCI_YOY" : 19.1631595692,
#     "MINORITY_TCI" : 2787404727.05,  归属于少数股东的综合收益总额
#     "MINORITY_TCI_YOY" : 4.8459336455,
#     "PRECOMBINE_TCI" : NaN,
#     "PRECOMBINE_TCI_YOY" : NaN,
#     "EFFECT_TCI_BALANCE" : NaN,
#     "EFFECT_TCI_BALANCE_YOY" : NaN,
#     "TCI_OTHER" : NaN,
#     "TCI_OTHER_YOY" : NaN,
#     "TCI_BALANCE" : NaN,
#     "TCI_BALANCE_YOY" : NaN,
#     "ACF_END_INCOME" : NaN,
#     "ACF_END_INCOME_YOY" : NaN,
#     "OPINION_TYPE" : "标准无保留意见" 审计意见(境内)
# https://emweb.securities.eastmoney.com/PC_HSF10/NewFinanceAnalysis/Index?type=web&code=sh600519#lrb-0
def get_em_benefit_api(symbol):
    stock_financial_benefit_ths_df = ak.stock_profit_sheet_by_report_em(symbol)
    stock_financial_benefit_ths_df = stock_financial_benefit_ths_df[[
        "SECUCODE",
        "SECURITY_CODE",
        "SECURITY_NAME_ABBR",
        "ORG_CODE",
        "ORG_TYPE",
        "REPORT_DATE",
        "REPORT_TYPE",
        "REPORT_DATE_NAME",
        "SECURITY_TYPE_CODE",
        "NOTICE_DATE",
        "UPDATE_DATE",
        "CURRENCY",
        "TOTAL_OPERATE_INCOME",
        "OPERATE_INCOME",
        "INTEREST_INCOME",
        "TOTAL_OPERATE_COST",
        "OPERATE_COST",
        "INTEREST_EXPENSE",
        "FEE_COMMISSION_EXPENSE",
        "RESEARCH_EXPENSE",
        "OPERATE_TAX_ADD",
        "SALE_EXPENSE",
        "MANAGE_EXPENSE",
        "FINANCE_EXPENSE",
        "FE_INTEREST_EXPENSE",
        "FE_INTEREST_INCOME",
        "FAIRVALUE_CHANGE_INCOME",
        "INVEST_INCOME",
        "ASSET_DISPOSAL_INCOME",
        "CREDIT_IMPAIRMENT_INCOME",
        "OTHER_INCOME",
        "OPERATE_PROFIT",
        "NONBUSINESS_INCOME",
        "NONBUSINESS_EXPENSE",
        "TOTAL_PROFIT",
        "INCOME_TAX",
        "NETPROFIT",
        "CONTINUED_NETPROFIT",
        "PARENT_NETPROFIT",
        'MINORITY_INTEREST',
        'DEDUCT_PARENT_NETPROFIT',
        'BASIC_EPS',
        'DILUTED_EPS',
        'OTHER_COMPRE_INCOME',
        'PARENT_OCI',
        'TOTAL_COMPRE_INCOME',
        'PARENT_TCI',
        'MINORITY_TCI',
        'OPINION_TYPE'
    ]]
    mongodb_util.insert_mongo(stock_financial_benefit_ths_df, 'stock_financial_benefit_ths_df')
    return stock_financial_benefit_ths_df


if __name__ == '__main__':
    get_em_benefit_api('SH600519')
    get_em_debt_api('SH600519')

    stock_cash_flow_sheet_by_report_em_df = ak.stock_cash_flow_sheet_by_report_em(symbol="SH600519")
    print(stock_cash_flow_sheet_by_report_em_df)
