# authentaication methods
SUPPORTED_AUTHENTITACTION_METHODS = ["password", "oauth"]
ACCOUNT_IDENTIFIER_ENV_VAR = "SNOWFLAKE_ACCOUNT_IDENTIFIER"
USER_ENV_VAR = "SNOWFLAKE_USER"
OAUTH_HOST_ENV_VAR = "SNOWFLAKE_OAUTH_HOST"
OAUTH_TOKEN_ENV_VAR = "SNOWFLAKE_OAUTH_TOKEN"

# optional args to remove boilerplate if you want to bake these into your @secrets
DATABASE_ENV_VAR = "SNOWFLAKE_DATABASE"
SCHEMA_ENV_VAR = "SNOWFLAKE_SCHEMA"
WAREHOUSE_ENV_VAR = "SNOWFLAKE_WAREHOUSE"