
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-14T04:29:50+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "598e96026e96b3f7cde6da8cc86fa1a16b767497",
 "version": "1.25.0.post0.dev128"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
