# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from perian.models.job_view_requirement_metadata import JobViewRequirementMetadata

class TestJobViewRequirementMetadata(unittest.TestCase):
    """JobViewRequirementMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobViewRequirementMetadata:
        """Test JobViewRequirementMetadata
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobViewRequirementMetadata`
        """
        model = JobViewRequirementMetadata()
        if include_optional:
            return JobViewRequirementMetadata(
                os_storage_config = perian.models.os_storage_config.OSStorageConfig(
                    size = 56, ),
                requirements = None
            )
        else:
            return JobViewRequirementMetadata(
        )
        """

    def testJobViewRequirementMetadata(self):
        """Test JobViewRequirementMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
