
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-14T08:18:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4bf2758209d0bc60b00fcaca9e258f8866aaa25e",
 "version": "2.36.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
