# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RevaGetReferences.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17RevaGetReferences.proto\x12\x0cRevaProtocol\"5\n\x18RevaGetReferencesRequest\x12\x19\n\x11\x61\x64\x64ress_or_symbol\x18\x01 \x01(\t\"K\n\x19RevaGetReferencesResponse\x12\x15\n\rreferences_to\x18\x01 \x03(\t\x12\x17\n\x0freferences_from\x18\x02 \x03(\t2~\n\x19RevaCrossReferenceService\x12\x61\n\x0eget_references\x12&.RevaProtocol.RevaGetReferencesRequest\x1a\'.RevaProtocol.RevaGetReferencesResponseB\x0f\n\rreva.protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RevaGetReferences_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rreva.protocol'
  _globals['_REVAGETREFERENCESREQUEST']._serialized_start=41
  _globals['_REVAGETREFERENCESREQUEST']._serialized_end=94
  _globals['_REVAGETREFERENCESRESPONSE']._serialized_start=96
  _globals['_REVAGETREFERENCESRESPONSE']._serialized_end=171
  _globals['_REVACROSSREFERENCESERVICE']._serialized_start=173
  _globals['_REVACROSSREFERENCESERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
