# coding: utf-8

"""
    Antimatter Public API

    Interact with the Antimatter Cloud API

    The version of the OpenAPI document: 1.2.0
    Contact: support@antimatter.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel
from pydantic import Field
from antimatter.client.models.tag import Tag
from antimatter.client.models.tag_set_span_tags_inner import TagSetSpanTagsInner
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class TagSet(BaseModel):
    """
    TagSet
    """ # noqa: E501
    capsule_tags: List[Tag] = Field(alias="capsuleTags")
    span_tags: List[TagSetSpanTagsInner] = Field(alias="spanTags")
    __properties: ClassVar[List[str]] = ["capsuleTags", "spanTags"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TagSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in capsule_tags (list)
        _items = []
        if self.capsule_tags:
            for _item in self.capsule_tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['capsuleTags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in span_tags (list)
        _items = []
        if self.span_tags:
            for _item in self.span_tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['spanTags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of TagSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "capsuleTags": [Tag.from_dict(_item) for _item in obj.get("capsuleTags")] if obj.get("capsuleTags") is not None else None,
            "spanTags": [TagSetSpanTagsInner.from_dict(_item) for _item in obj.get("spanTags")] if obj.get("spanTags") is not None else None
        })
        return _obj


