__all__ = ["GlobNames"]


class GlobNames:
    MODELS = "model"
    DOFSPACE = "dofSpace"
    MESHSHAPE = "meshShape"
    MESHRANK = "meshRank"
    ESET = "elemSet"
    NSET = "nodeSet"
    NGROUPS = "nodeGroups"
    EGROUPS = "elemGroups"
    MODELFACTORY = "modelFactory"
    MODULEFACTORY = "moduleFactory"
    SHAPEFACTORY = "shapeFactory"
    SOLVERFACTORY = "solverFactory"
    PRECONFACTORY = "preconFactory"
    TIMESTEP = "timeStep"
    STATE0 = "state0"
    EXTFORCE = "extForce"
    CONSTRAINTS = "constraints"
    OLDSTATE0 = "oldstate0"
    BACKUPSTATE0 = "backupstate0"
    HISTORY = "history"
    MATRIX0 = "matrix0"
    MATRIX2 = "matrix2"
    MATRIXB = "matrixB"
    TABLES = "tables"
    ELEMTABLES = "elemTables"
    LAMBDA = "lambda"
    MODULEDATA = "module"
    SLIDERS = "sliders"
    ACCEPTED = "accepted"
    LBFACTORS = "lbFactors"
