# coding: utf-8

"""
    Notehub API

    The OpenAPI definition for the Notehub.io API. 

    The version of the OpenAPI document: 1.0.0
    Contact: engineering@blues.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.models.create_monitor import CreateMonitor

class TestCreateMonitor(unittest.TestCase):
    """CreateMonitor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMonitor:
        """Test CreateMonitor
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMonitor`
        """
        model = CreateMonitor()
        if include_optional:
            return CreateMonitor(
                uid = '',
                name = '',
                description = '',
                source_type = 'event',
                disabled = True,
                alert = True,
                notefile_filter = [
                    ''
                    ],
                fleet_filter = [
                    ''
                    ],
                source_selector = 'body.temperature',
                condition_type = 'greater_than',
                thresholds = notehub_py.models.monitor_thresholds.Monitor_thresholds(
                    alarm = 1.337, ),
                alert_routes = [
                    notehub_py.models.monitor_alert_routes_inner.Monitor_alert_routes_inner(
                        email_addresses = [
                            ''
                            ], )
                    ],
                last_routed_at = '',
                silenced = True,
                routing_cooldown_period = '10m or 5h30m40s'
            )
        else:
            return CreateMonitor(
                name = '',
                description = '',
                notefile_filter = [
                    ''
                    ],
                alert_routes = [
                    notehub_py.models.monitor_alert_routes_inner.Monitor_alert_routes_inner(
                        email_addresses = [
                            ''
                            ], )
                    ],
        )
        """

    def testCreateMonitor(self):
        """Test CreateMonitor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
