# coding: utf-8

"""
    Notehub API

    The OpenAPI definition for the Notehub.io API. 

    The version of the OpenAPI document: 1.0.0
    Contact: engineering@blues.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from notehub_py.api.firmware_api import FirmwareApi


class TestFirmwareApi(unittest.TestCase):
    """FirmwareApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FirmwareApi()

    def tearDown(self) -> None:
        pass

    def test_get_firmware_info(self) -> None:
        """Test case for get_firmware_info

        """
        pass


if __name__ == '__main__':
    unittest.main()
