
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-13T15:45:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7488c12082d598e5f71bec9260ee374b6cb30cce",
 "version": "1.25.0.post0.dev123"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
