
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-15T19:44:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "74517681684ee2648fb7bc7ce38ec5ad40c1b3e1",
 "version": "1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
