
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-15T18:52:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "03435db3cbc1b8840f1c1fa1d95b9ef4b1a71796",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
