
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-14T03:52:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "01a26c71b2862fd800c0e60c4240841c6b2b279c",
 "version": "1.25.0.post0.dev125"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
