# Generated by Django 3.2.12 on 2022-02-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circuits', '0004_rename_cable_peer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='extra-files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='circuits', to='circuits.circuit')),
            ],
        ),
    ]
