# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class OrderLiftType(str, Enum):
    """
    Тип подъема заказа на этаж:  * `NOT_NEEDED` — не требуется. * `MANUAL` — ручной. * `ELEVATOR` — лифт. * `CARGO_ELEVATOR` — грузовой лифт. * `FREE` — любой из перечисленных выше, если включена опция бесплатного подъема. 
    """

    """
    allowed enum values
    """
    NOT_NEEDED = 'NOT_NEEDED'
    MANUAL = 'MANUAL'
    ELEVATOR = 'ELEVATOR'
    CARGO_ELEVATOR = 'CARGO_ELEVATOR'
    FREE = 'FREE'
    UNKNOWN = 'UNKNOWN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderLiftType from a JSON string"""
        return cls(json.loads(json_str))


