# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class OrderSubsidyType(str, Enum):
    """
    Тип субсидии, которые дает Маркет:  * `SBER_SPASIBO` — компенсация при оплате заказа бонусами СберСпасибо. Не используется с июля 2021 года. * `YANDEX_CASHBACK` — компенсация при оплате заказа баллами Плюса. * `SUBSIDY` — компенсация скидки:   * по промокодам;   * по купонам;   * по акциям. * `DELIVERY` — компенсация стоимости доставки магазину, который работает по модели DBS. 
    """

    """
    allowed enum values
    """
    NOT_SUBSIDY = 'NOT_SUBSIDY'
    SBER_SPASIBO = 'SBER_SPASIBO'
    YANDEX_CASHBACK = 'YANDEX_CASHBACK'
    SUBSIDY = 'SUBSIDY'
    DELIVERY = 'DELIVERY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderSubsidyType from a JSON string"""
        return cls(json.loads(json_str))


