# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class TurnoverType(str, Enum):
    """
    Оценка оборачиваемости.  |enum|Диапазон оборачиваемости|Комментарий| |-|-|-| |`LOW`|`turnoverDays` ≥ 120|| |`ALMOST_LOW`|100 ≤ `turnoverDays` < 120|| |`HIGH`|45 ≤ `turnoverDays` < 100|| |`VERY_HIGH`|0 ≤ `turnoverDays` < 45|| |`NO_SALES`|—|Продаж нет.| |`FREE_STORE`|Любое значение.|Товары этой категории сейчас хранятся бесплатно.| 
    """

    """
    allowed enum values
    """
    LOW = 'LOW'
    ALMOST_LOW = 'ALMOST_LOW'
    HIGH = 'HIGH'
    VERY_HIGH = 'VERY_HIGH'
    NO_SALES = 'NO_SALES'
    FREE_STORE = 'FREE_STORE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TurnoverType from a JSON string"""
        return cls(json.loads(json_str))


