
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-17T22:13:12+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "25e78a2b3d2333f7effad7ae3ca2d45e5081e82b",
 "version": "1.3.1rc8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
