from ralium.webpage import WebHook
from ralium.config import WindowConfig

import webview

class Window:
    def __init__(self, webhooks: list[WebHook], config: WindowConfig | None = None) -> None: ...
    
    def load_handler(self, window: webview.Window) -> None: ...
    def shutdown(self) -> None: ...
    def display(self, url: str) -> None: ...
    def update(self) -> None: ... 
    def start(self) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...