# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class OfferProcessingStatusType(str, Enum):
    """
    Статус публикации товара:  * `READY` — товар прошел модерацию. Чтобы разместить его на Маркете, установите для него цену. * `IN_WORK` — товар проходит модерацию. Это занимает несколько дней. * `NEED_CONTENT` — для товара без SKU на Маркете `marketSku` нужно найти карточку самостоятельно (через API или личный кабинет магазина) или создать ее, если товар еще не продается на Маркете. * `NEED_INFO` — товар не прошел модерацию из-за ошибок или недостающих сведений в описании товара. Информация о причинах отклонения возвращается в параметре `notes`. * `REJECTED` — товар не прошел модерацию, так как Маркет не планирует размещать подобные товары. * `SUSPENDED` — товар не прошел модерацию, так как Маркет пока не размещает подобные товары. 
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    READY = 'READY'
    IN_WORK = 'IN_WORK'
    NEED_INFO = 'NEED_INFO'
    NEED_MAPPING = 'NEED_MAPPING'
    NEED_CONTENT = 'NEED_CONTENT'
    CONTENT_PROCESSING = 'CONTENT_PROCESSING'
    SUSPENDED = 'SUSPENDED'
    REJECTED = 'REJECTED'
    REVIEW = 'REVIEW'
    CREATE_ERROR = 'CREATE_ERROR'
    UPDATE_ERROR = 'UPDATE_ERROR'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OfferProcessingStatusType from a JSON string"""
        return cls(json.loads(json_str))


