# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class OfferCardStatusType(str, Enum):
    """
    Статус карточки товара:  * HAS_CARD_CAN_NOT_UPDATE — **Карточка Маркета**. * HAS_CARD_CAN_UPDATE — **Можно дополнить**. * HAS_CARD_CAN_UPDATE_ERRORS — **Изменения не приняты**. * HAS_CARD_CAN_UPDATE_PROCESSING — **Изменения на проверке**. * NO_CARD_NEED_CONTENT — **Создайте карточку**. * NO_CARD_MARKET_WILL_CREATE — **Создаст Маркет**. * NO_CARD_ERRORS — **Не создана из-за ошибки**. * NO_CARD_PROCESSING — **Проверяем данные**. * NO_CARD_ADD_TO_CAMPAIGN — **Разместите товар в магазине**.  [Что обозначает каждый из статусов](https://yandex.ru/support/marketplace/assortment/content/statuses.html) 
    """

    """
    allowed enum values
    """
    HAS_CARD_CAN_NOT_UPDATE = 'HAS_CARD_CAN_NOT_UPDATE'
    HAS_CARD_CAN_UPDATE = 'HAS_CARD_CAN_UPDATE'
    HAS_CARD_CAN_UPDATE_ERRORS = 'HAS_CARD_CAN_UPDATE_ERRORS'
    HAS_CARD_CAN_UPDATE_PROCESSING = 'HAS_CARD_CAN_UPDATE_PROCESSING'
    NO_CARD_NEED_CONTENT = 'NO_CARD_NEED_CONTENT'
    NO_CARD_MARKET_WILL_CREATE = 'NO_CARD_MARKET_WILL_CREATE'
    NO_CARD_ERRORS = 'NO_CARD_ERRORS'
    NO_CARD_PROCESSING = 'NO_CARD_PROCESSING'
    NO_CARD_ADD_TO_CAMPAIGN = 'NO_CARD_ADD_TO_CAMPAIGN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OfferCardStatusType from a JSON string"""
        return cls(json.loads(json_str))


