# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class OrderVatType(str, Enum):
    """
    Ставка налога на добавленную стоимость (НДС) на услугу доставки заказа:  * `NO_VAT` — НДС не облагается, используется только для отдельных видов услуг.  * `VAT_0` — НДС 0%. Например, используется при продаже товаров, вывезенных в таможенной процедуре экспорта, или при оказании услуг по международной перевозке товаров.  * `VAT_10_110` — НДС 10/110. Расчетная ставка НДС 10%, применяется только для случая предоплаты.  * `VAT_20_120` — НДС 20/120. Расчетная ставка НДС 20%, применяется только для случая предоплаты.  * `VAT_18_118` — НДС 18/118. Ставка использовалась до 1 января 2019 года.  Используется только совместно с параметром `payment-method=YANDEX`. 
    """

    """
    allowed enum values
    """
    VAT_18 = 'VAT_18'
    VAT_10 = 'VAT_10'
    VAT_18_118 = 'VAT_18_118'
    VAT_10_110 = 'VAT_10_110'
    VAT_0 = 'VAT_0'
    NO_VAT = 'NO_VAT'
    VAT_20 = 'VAT_20'
    VAT_20_120 = 'VAT_20_120'
    UNKNOWN_VALUE = 'UNKNOWN_VALUE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderVatType from a JSON string"""
        return cls(json.loads(json_str))


