# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class PriceQuarantineVerdictParamNameType(str, Enum):
    """
    Имя параметра причины скрытия товара по цене. * `CURRENT_PRICE` — цена, из-за которой товар попал в карантин; * `LAST_VALID_PRICE` — последняя цена до попадания в карантин (только для карантина типа `PRICE_CHANGE`); * `MIN_PRICE` — порог попадания в карантин (только для карантина типов `LOW_PRICE` и `LOW_PRICE_PROMO`); * `CURRENCY` — валюта. 
    """

    """
    allowed enum values
    """
    CURRENT_PRICE = 'CURRENT_PRICE'
    LAST_VALID_PRICE = 'LAST_VALID_PRICE'
    MIN_PRICE = 'MIN_PRICE'
    CURRENCY = 'CURRENCY'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PriceQuarantineVerdictParamNameType from a JSON string"""
        return cls(json.loads(json_str))


