# coding: utf-8

"""
    Партнерский API Маркета

    API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов. 

    The version of the OpenAPI document: LATEST
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class RegionType(str, Enum):
    """
    Тип региона.  Возможные значения:  * `CITY_DISTRICT` — район города.  * `CITY` — крупный город.  * `CONTINENT` — континент.  * `COUNTRY_DISTRICT` — область.  * `COUNTRY` — страна.  * `REGION` — регион.  * `REPUBLIC_AREA` — район субъекта федерации.  * `REPUBLIC` — субъект федерации.  * `SUBWAY_STATION` — станция метро.  * `VILLAGE` — город.  * `OTHER` — неизвестный регион. 
    """

    """
    allowed enum values
    """
    OTHER = 'OTHER'
    CONTINENT = 'CONTINENT'
    REGION = 'REGION'
    COUNTRY = 'COUNTRY'
    COUNTRY_DISTRICT = 'COUNTRY_DISTRICT'
    REPUBLIC = 'REPUBLIC'
    CITY = 'CITY'
    VILLAGE = 'VILLAGE'
    CITY_DISTRICT = 'CITY_DISTRICT'
    SUBWAY_STATION = 'SUBWAY_STATION'
    REPUBLIC_AREA = 'REPUBLIC_AREA'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of RegionType from a JSON string"""
        return cls(json.loads(json_str))


