# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openobd_protocol/SessionController/Session.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from openobd_protocol import Status_pb2 as openobd__protocol_dot_Status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0openobd_protocol/SessionController/Session.proto\x12/com.jifeline.OpenOBD.Protocol.SessionController\x1a\x1dopenobd_protocol/Status.proto\"\'\n\x0cStartSession\x12\x17\n\x0f\x63onnection_uuid\x18\x01 \x01(\t\"r\n\x0bSessionInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x15\n\rgrpc_endpoint\x18\x04 \x01(\t\x12\x1c\n\x14\x61uthentication_token\x18\x05 \x01(\t\"]\n\x0c\x41uthenticate\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\x12\x12\n\ncluster_id\x18\x04 \x01(\t\"\x1d\n\x0cSessionToken\x12\r\n\x05token\x18\x01 \x01(\t\"a\n\x0fSessionInfoList\x12N\n\x08sessions\x18\x01 \x03(\x0b\x32<.com.jifeline.OpenOBD.Protocol.SessionController.SessionInfo\"\x17\n\tSessionId\x12\n\n\x02id\x18\x01 \x01(\tB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'openobd_protocol.SessionController.Session_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_STARTSESSION']._serialized_start=132
  _globals['_STARTSESSION']._serialized_end=171
  _globals['_SESSIONINFO']._serialized_start=173
  _globals['_SESSIONINFO']._serialized_end=287
  _globals['_AUTHENTICATE']._serialized_start=289
  _globals['_AUTHENTICATE']._serialized_end=382
  _globals['_SESSIONTOKEN']._serialized_start=384
  _globals['_SESSIONTOKEN']._serialized_end=413
  _globals['_SESSIONINFOLIST']._serialized_start=415
  _globals['_SESSIONINFOLIST']._serialized_end=512
  _globals['_SESSIONID']._serialized_start=514
  _globals['_SESSIONID']._serialized_end=537
# @@protoc_insertion_point(module_scope)
